layer2:
  common:
    mgmt_vlan:
      id: 9
      network: 10.9.9.0
      mask: 255.255.255.0
      gateway: 10.9.9.1
      nameservers:
        - 10.9.9.1
      domain: leigh.delamere
    vlans:
      6: wan
      7: client_lan
      8: guest_lan
      9: core_lan
      4094: no_native_untagged  # native vlan is tagging is global setting, use this dummy vlan to effectively disable per-interface
  cisco-1:
    address: 10.9.9.5
    ports:
      1:
        desc: burglar alarm
        vlan: 8
      2:
        desc: french-room-ap
        vlan: 1
        trunk: true
      3:
        desc: back-stairs-ap
        vlan: 1
        trunk: true
      4:
        desc: front-stairs-ap
        vlan: 1
        trunk: true
      5:
        vlan: 1
      6:
        vlan: 7
      7:
        vlan: 9
      8:
        desc: pikvm
        vlan: 9
      9:
        desc: proxbox
        vlan: 4094  # tag all real vlans
        trunk: true
      10:
        desc: wan_trunk
        vlan: 6
        trunk: true
  cisco-2:
    address: 10.9.9.6
    ports:
      1:
        desc: green-study-ap
        vlan: 1
        trunk: true
      2:
        vlan: 7
      3:
        vlan: 7
      4:
        vlan: 7
      5:
        vlan: 7
      6:
        vlan: 7
      7:
        vlan: 7
      8:
        vlan: 7
      9:
        desc: wan_trunk
        vlan: 6
        trunk: true
      10:
        desc: wan_trunk
        vlan: 6
        trunk: true
